export const PLANT_ENERGY_GAIN_PER_SECOND = 0.1;
export const PLANT_SEED_ENERGY = 1;
export const PLANT_SEEDING_ENERGY = 100;
export const PLANT_SEEDING_SEED_COUNT = 50;
export const PLANT_SEEDING_RANGE = 100;
export const PLANT_GROWTH_DENSITY = 1 / (4 * 4);

export const PLANT_INITIAL_DENSITY = 0.001;

export const PLANT_COLOR = "#00FF00";

const ANIMAL_INITIAL_RADIUS = 3;
const ANIMAL_INITIAL_VOLUME = 4 / 3 * Math.PI * (ANIMAL_INITIAL_RADIUS ** 3);
const ANIMAL_ENERGY_PER_VOLUME = 125;
export const ANIMAL_INITIAL_ENERGY = ANIMAL_INITIAL_VOLUME * ANIMAL_ENERGY_PER_VOLUME;
export const ANIMAL_MULTIPLY_AT_ENERGY = 3 * ANIMAL_INITIAL_ENERGY;
export const ANIMAL_SURVIVAL_ENERGY = 0.5 * ANIMAL_INITIAL_ENERGY;

export const ANIMAL_COLOR = "#0000FF";

export const ANIMAL_DEFAULT_MOVEMENT_SPEED = 10;

export const MOVEMENT_COST = 0.01; // mass * distance